# Generated by Django 4.2.3 on 2023-11-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_remove_clases_tipo_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clases',
        ),
    ]
