# Generated by Django 4.2.3 on 2023-11-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorial', '0003_delete_clases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='productos')),
                ('prec', models.IntegerField(default='0')),
            ],
        ),
    ]
